### ISSUE TITLE
Make Expiry and Renewal dates optional?

### ISSUE THREAD

**Issue by froger-me** [michelve/software-license-manager#1]
Hello,

First of all, I've gotta say good job for the fork: I was thinking about doing it myself, because of the issue described more in details below more particularly, but also generally because of the way the plugin is coded as a whole. The functionalities are great and do work, but a rewrite in OOP and more integration look awfully necessary. Your fork is a huge step towards a better, cleaner code base.

Onto the issue at hand: when adding/editing a license, the Expiry and Renewal dates are automatically set to `$current_date_plus_1year` just like in the original code base. Why is it the case in you opinion? Cannot it be optional?

Use case, on the same install with auto-expiry:
* **A client bought a 1 year Limited License for a theme**, I’m querying for the license that should expire, I can show all the relevant information, everything is fine.
* **The same client bought a Lifetime Premium License for a plugin**, I’m querying for the license that should not expire, and yet there is still an expiry and renewal date when displaying license info (irrelevant data), and when the expiry date is reached, auto-expire is triggered.

**=> unhappy client**

Can’t we just remove the following lines to avoid unnecessary assumptions?

```php
if(empty($renewed_date)){
   $renewed_date = $current_date;
}
if(empty($expiry_date)){
    $expiry_date = $current_date_plus_1year;
}
```

Best,
froger-me

**Comment by michelve** [comment]
Thank you @froger-me for the feedback, will definitely include this on version 4.5

**Comment by michelve** [comment]
@froger-me - we have added support for license type

lic_type: lifetime, subscription

![screen shot 2018-12-02 at 10 12 31 pm](https://user-images.githubusercontent.com/4137743/49351032-7dffdd80-f67f-11e8-9857-520ff5180389.png)

**Comment by froger-me** [comment]
Hi @michelve !
Just FYI, I rolled with my own solution in [WP Plugin Update Server](https://wordpress.org/plugins/wp-plugin-update-server) instead of relying on a 3rd party.
However, all in all, it is great news for your users!
