### ISSUE TITLE
Integrate with WooCommerce Subscriptions

### ISSUE THREAD

**Issue by paulmiller3000** [michelve/software-license-manager#10]
Does SLM integrate with WooCommerce Subscriptions? It doesn't appear to, but I thought I'd ask. We're using it to charge customers annually for their plugins. 

If not, we'll take it on and potentially submit a pull request as well. Here's our thinking:

1. Add a new Product Data option to WooCommerce called "Licensed Simple Subscription."
2. Should include all of the fields from the WooCommerce Simple Subscription type but should also trigger the licensing functions from the SLM License Product type
3. Every time a subscription is automatically renewed, it should also extend the license by the appropriate amount. For example, if a subscription charges every year, then the license expiration date should move forward by one year at the same time. 

Thanks!

**Comment by michelve** [comment]
Hello @paulmiller3000 

I had this on my backlog a while ago, i just have not have the time lately, but if this is something you want to take on you are more than welcome i will also allow your pull request as well, as this is a great feature to have. Thanks.

**Comment by paulmiller3000** [comment]
> Hello @paulmiller3000
> 
> I had this on my backlog a while ago, i just have not have the time lately, but if this is something you want to take on you are more than welcome i will also allow your pull request as well, as this is a great feature to have. Thanks.

Awesome; I'll try to get to this in the next week or two. Thanks!

**Comment by paulmiller3000** [comment]
@michelve So sorry we did not get to this; got slammed with a project that took quite a bit longer than expected!

**Comment by trescatorce** [comment]
What a pity this change did not come to fruition!
It would be wonderful to see it implemented in the future.
Unfortunately I do not have the basic knowledge to undertake this task
I love this plug-in, did I say that already?
