### ISSUE TITLE
License Status empty no choices 

### ISSUE THREAD

**Issue by ricardo777** [michelve/software-license-manager#104]
**Describe the bug**

When editing or creating a new license key the option "License Status" is emtpy so no choice can be made.

**To Reproduce**

1. Go to 'edit or create new license'
2. Click on 'License Status'
3. See error

**Expected behavior**

Set of options

**Screenshots**

![Schermafbeelding 2024-12-18 104404](https://github.com/user-attachments/assets/5ca36ccf-fc71-4a04-b51e-e6f4b85b41a0)

**Desktop (please complete the following information):**

Latest Chrome version on Windows 11

**Additional context**
Need more information please ask so I can provide.

**Comment by ricardo777** [comment]
Some more information, I upgraded from the old version 6.1.9 to 6.3.4. I checking the tables but I dont see 'lic_status_tbl' in my database.

![Schermafbeelding 2024-12-18 105246](https://github.com/user-attachments/assets/a119fd1a-40eb-4cc6-b05b-1ef4909d4fc6)

**Comment by michelve** [comment]
it seems lic_status_tbl failed to create when you did the upgrade, i will take a look - thx

**Comment by ricardo777** [comment]
Hi @michelve thank you, tested and now it is working.
