### ISSUE TITLE
Integration with newest WooCommerce not working

### ISSUE THREAD

**Issue by QuiNz0r** [michelve/software-license-manager#11]
Plugin doesn't show it's license properties when trying to create a product, so it's not usable
right now with the newest WordPress and WooCommerce versions.

**Comment by QuiNz0r** [comment]
It's because of SLM 5.1.5.

5.1.4 works fine

**Comment by michelve** [comment]
thanks @QuiNz0r - i been off for a while now, i will soon check compatinilitlies issues with the latest versions of woo and wp. Thanks for reporting this issue.

**Comment by michelve** [comment]
fixed on version 5.1.6
