### ISSUE TITLE
Log and export option

### ISSUE THREAD

**Issue by flopezinc** [michelve/software-license-manager#13]
I received the following message in the mail

Hi!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site and notifies you using this automatic email.

In this case, WordPress has detected an error with one of your plugins, Software License Manager.

First, visit your website (https://w.com/) and check if there is any visible problem. Next, visit the page where the error was detected (https://w.com/wp-admin/admin.php?page=slm_manage_license&edit_record=14) and check if there is any visible problem.

When you seek help for this problem, you may be asked for the following information:
WordPress version 5.3.2
Current topic: Fagri (version 1.0.6)
Current plugin: Software License Manager (version 5.1.7)
PHP version 7.3.13

Error details
==================
An error of type E_ERROR has occurred on line 572 of the file /h/www/w.com/wp-content/plugins/software-license-manager-5.1.7/admin/slm-add-licenses.php . Error message: Uncaught Error: Cannot use object of type WP_Error as array in /h/w/w.com/wp-content/plugins/software-license-manager-5.1.7/admin/slm-add-licenses .php: 572
Stack trace:
# 0 /h/w/w.com/wp-includes/class-wp-hook.php(288): slm_add_licenses_menu ('')
# 1 /h/w/w.com/wp-includes/class-wp-hook.php(312): WP_Hook-> apply_filters ('', Array)
# 2 /h/w/w.com/wp-includes/plugin.php(478): WP_Hook-> do_action (Array)
# 3 /h/w/w.com/wp-admin/admin.php(254): do_action ('slm_page_slm_ma ...')
# 4 {main}
  thrown

**Comment by michelve** [comment]
Thank you @flopezinc - i will look this issue right away.

**Comment by michelve** [comment]
@flopezinc - i just release version 5.1.8, could you try again and let me know?

release: https://github.com/michelve/software-license-manager/releases/tag/5.1.8
