### ISSUE TITLE
Complete order email displays incorrect expiration date info

### ISSUE THREAD

**Issue by trescatorce** [michelve/software-license-manager#14]
**Describe the bug**

1. The customer buys a monthly license of my product
2. The license is correctly generated in SLM and it is verified that it is activated for 30 days
3. Woocommerce order details displays expiration date OK
4. But the email that woocommerce generates informing that the order is completed indicates:
    - PRODUCT: My software name (valid for 1 month)
    - EXPIRES: NEVER
    - DOWNLOAD: url to download my software

**Expected behavior**
Is it possible to include the license expiration date where it currently says "NEVER"?

**Screenshots**
- Received email: https://i.imgur.com/TMEP3bK.png
- SLM licence generated info: https://i.imgur.com/aYyYtQ4.png
- Woocommerce order details: https://i.imgur.com/r3Oyg8k.png

**WP, WOOCOMMERCE AND SLM VERSIONS**
- WP: 5.3.2
- WOOCOMMERCE: 3.9.1
- SLM: 5.1.8

Thank you for your work!

**Comment by michelve** [comment]
Hello @trescatorce 
when you create the product are you setting license type as: subscription or lifetime ?

here is an example i did when i set to subscription and with a date: https://d.pr/free/i/0gOUhY work as expected.

**Comment by michelve** [comment]
also taking another look closely, the download section comes from the download limit and download expire those are woocommrce settings, not the plugin settings, so if u leave empty it will never expire.

https://d.pr/free/i/ob25oI

**Comment by trescatorce** [comment]
Thank you, michelve! I had the download section blank. I apologize for my failure.

On the other hand, I have detected that, with the plugin activated, when you add a New Product, by default you get Simple Product with the General tab (this is ok).
But if you switch to License Product and go back to Simple Product, the General tab disappears

A quick gif :) : [https://i.imgur.com/4pgqvAX.gif](url)
