### ISSUE TITLE
devices and domains menu

### ISSUE THREAD

**Issue by flopezinc** [michelve/software-license-manager#16]
Hi
Update the plugin to the latest version, update Secret Key for Creation and Secret Key for Verification, but in the existing licenses in the devices and domains menu they appear blank, when consulting the export menu and see the log there if it shows the information of the site that is using it

![imagen](https://user-images.githubusercontent.com/4023609/76467185-a7450880-63ae-11ea-9de6-67c4db450028.png)
![imagen](https://user-images.githubusercontent.com/4023609/76467942-64843000-63b0-11ea-961e-38800b8077f4.png)

regards

**Comment by michelve** [comment]
hello @flopezinc - will take a look at this, thanks for reporting this issue, for some reason i did not received a notification for this ticket.

**Comment by michelve** [comment]
issues fixed and resolved
