### ISSUE TITLE
License Manager Add or Edit Tabs not working

### ISSUE THREAD

**Issue by Simulator88** [michelve/software-license-manager#20]
**Describe the bug**
If you'd like add a new license and you click on the tabs of User information, product etc it simply does not open it.

**To Reproduce**
1. Go to add or manage license
2. Click on any on the tabs on the left hand side
3. See error, nothing changing.

**Expected behavior**
It should load a new tab on the right.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Latest Google Chrome
 - Version 5,3.2

**Comment by Simulator88** [comment]
Ok, It seems like I found the solution. There are some themes which are already include bootstrap.min.js or bootstrap.js. There should be an option if you would like to load it or not.

**Comment by michelve** [comment]
@Simulator88 , yes deff, an option in the settings panel to load or not load the boostrap librray.

**Comment by michelve** [comment]
fixed in version 5.4.1
