### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by mbrsolution** [michelve/software-license-manager#22]
Thank you for providing this fork with language features added. However I have found that some strings are currently not translatable. I was wondering if you could check this. Once this is fixed I will submit an updated Spanish po and mo language files.

If you need more information please let me know. 

Kind regards

**Comment by michelve** [comment]
@mbrsolution - deff  - im still working on it - prob by end of week all strings will be working

**Comment by michelve** [comment]
could you try again and let me know, thx
