### ISSUE TITLE
how users can control his information?

### ISSUE THREAD

**Issue by Nemra1** [michelve/software-license-manager#23]
The plugin is very useful but i have some question!
is there is client panel can allowed to the users to check the license information inside the user account?
i mean user A after register in my site... he can see his own license information in his panel

**Comment by michelve** [comment]
yes there is, you will need to install woocommerce for that, they will have access to their liceses and info, see screenshot: https://raw.githubusercontent.com/michelve/software-license-manager/1bf014b84300ba58e7ce614c25f9976c7fab6cb1/public/assets/images/previews/my-account-lics-opened.png

**Comment by Nemra1** [comment]
@michelve  exactly this is what am looking for..thank you
