### ISSUE TITLE
How to use with WP Plugin Update Server

### ISSUE THREAD

**Issue by ali110309** [michelve/software-license-manager#27]
I use the **WP Plugin Update Server** to provide updates to my plugins and theme, and on the user side I used the `plugin-update-checker`.
Now how can I integrate the WP Plugin Update Server with your plugin?
I want my users to be able to update plugins by entering a license
Please advise on this
Thank you for your efforts

**Comment by michelve** [comment]
@ali110309 - here are some samples - https://github.com/michelve/software-license-manager/wiki/Check-license---sample

also see the sidebar for more demos
