### ISSUE TITLE
date() is used in this plugin. Would you mind using wp_date() introduced in WP 5.3?

### ISSUE THREAD

**Issue by k-kikuchi-waverworks** [michelve/software-license-manager#29]
Thank you for providing very good product. I have found that your plugin still use date(), this may cause a issue for locale excerpt for US above WP 5.3. Would you mind using wp_date() introduced in WP 5.3 ?

https://developer.wordpress.org/reference/functions/wp_date/

Kings Regards

**Comment by michelve** [comment]
i will release this in the next release 5.5.8 thx

**Comment by k-kikuchi-idea-hack** [comment]
Thank you for your working. I will wait for the release.
Maybe, you simply just have to only have to replace date() with wp_date().

Regards

**Comment by michelve** [comment]
implemented in next release https://github.com/michelve/software-license-manager/commit/af90004fc95cf978cca3edb2298039735898749f
