### ISSUE TITLE
 5.0.2 source code has software-license-manager inside software-license-manager

### ISSUE THREAD

**Issue by smrtreddyk** [michelve/software-license-manager#3]
Hi Michelve,

Not sure if i am doing this right, i took the source code i.e."https://github.com/michelve/software-license-manager/archive/5.0.2.zip" and tried to upload it into wordpress and i got "The plugin does not have a valid header.  " error. when i googled online it looks like this error happens if plugin folder exists inside plugin, sure thing this zip file has "software-license-manager" inside "software-license-manager"

Could you please fix this?

reference:
https://chattymango.com/how-fix-wordpress-error-plugin-not-valid-header/

**Comment by michelve** [comment]
@smrtreddyk - get the latest version from here - https://github.com/michelve/software-license-manager/releases/tag/5.0.2-patched once extracted rename the folder from software-license-manager-5.0.2-patched to software-license-manager

**Comment by smrtreddyk** [comment]
That worked thank you, i didn't had to rename the folder it still worked.

**Comment by smrtreddyk** [comment]
I was able to install but now my complete website is down with message as "The site is experiencing technical difficulties."

**Comment by michelve** [comment]
i pushed version 5.0.3 it includes some missing files, also can you tell me your wp version and php version, also if you can share the error log file. Try the latest version and let me know.

**Comment by smrtreddyk** [comment]
5.0.3 also same issue "The site is experiencing technical difficulties."

FYI for security purpose replaced my website with ******c in below error log

Error Details:
PHP Version: PHP 7.0
WP Version: 5.2
Error Log:
[28-Jul-2019 19:40:23 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function is_account_page() in /home2/******c/public_html/staging/9045/wp-content/plugins/software-license-manager-5.0.3/includes/slm-scripts.php:19
Stack trace:
#0 /home2/******c/public_html/staging/9045/wp-includes/class-wp-hook.php(286): slm_frontend_assets('')
#1 /home2/******c/public_html/staging/9045/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /home2/******c/public_html/staging/9045/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home2/******c/public_html/staging/9045/wp-includes/script-loader.php(2537): do_action('wp_enqueue_scri...')
#4 /home2/******c/public_html/staging/9045/wp-includes/class-wp-hook.php(286): wp_enqueue_scripts('')
#5 /home2/******c/public_html/staging/9045/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home2/******c/public_html/staging/9045/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#7 /home2/******c/public_html/staging/9045/wp-includes/general-template.php(2 in /home2/******c/public_html/staging/9045/wp-content/plugins/software-license-manager-5.0.3/includes/slm-scripts.php on line 19

**Comment by michelve** [comment]
i see, 2 things rename plugin from software-license-manager-5.0.3 to software-license-manager, and for now enable woocommerce plugin i will release a patch for the woocommerce dependency that should solve your issue

**Comment by michelve** [comment]
@smrtreddyk - this issue has been solved in version 5.0.4
