### ISSUE TITLE
Software License Manager changes theme

### ISSUE THREAD

**Issue by Dultus** [michelve/software-license-manager#30]
**Describe the bug**
Quite selfexplanatory via screenshots.
The plugin causes my theme to place all words under each other instead of line wise like on the second screenshot.

**To Reproduce**
- Impreza Theme installed. Using this plugin causes that issue.

**Expected behavior**
Addresses should be looking nice like usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/37348379/91324819-c7cd1780-e7c2-11ea-8174-7c88f2615401.png)
![image](https://user-images.githubusercontent.com/37348379/91324906-e03d3200-e7c2-11ea-933f-25c270537fe7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi

**Additional context**
I'd be really grateful for a fix from your side - I'm quite certain multiple themes will have that issue.
Sadly yours is the only license manager plugin that does actually work for me and does a very good job.
Thank you in advance!

**Comment by michelve** [comment]
@Dultus - what theme are you currently using  ?

**Comment by Dultus** [comment]
> @Dultus - what theme are you currently using  ?

As written the Impreza Theme.

**Comment by michelve** [comment]
fixed in version 5.5.7
