### ISSUE TITLE
my license

### ISSUE THREAD

**Issue by rigler86** [michelve/software-license-manager#32]
when trying to view my license under my account on the Wordpress site it tries to expand then stops and reloads page.

**Comment by michelve** [comment]
make sure you have turn off conflict mode on

**Comment by rigler86** [comment]
> make sure you have turn off conflict mode on 

Where would this be?

**Comment by michelve** [comment]
In SLM menu > settings

look into:
Bootstrap library and integrations

**Comment by rigler86** [comment]
Ok, thank you ror the reply. I will look into that

**Comment by rigler86** [comment]
after disabling bootstrap im still having the same issue. what else can i try?

**Comment by rigler86** [comment]
> In SLM menu > settings
> 
> look into:
> Bootstrap library and integrations
> 
> 
> 
> 

[received_325285462058528.gif](https://user-images.githubusercontent.com/67995446/93531828-d87a3480-f90d-11ea-83ed-abf42a597d35.gif)
