### ISSUE TITLE
Would you mind using home_url instead of site_url

### ISSUE THREAD

**Issue by k-kikuchi-idea-hack** [michelve/software-license-manager#39]
Hello
Thank you for providing good plugin and quick support for bug fix.

I looked into your code to check following issue
https://github.com/michelve/software-license-manager/issues/33
https://github.com/michelve/software-license-manager/issues/38

and. I realized that you use site_url instead of home_url.

Multilingual plugins like Bogo, WPML, Polylang use home_url to apply their filter hook to activate multilingual feature.

so, would mind using home_url instead of site_url ?
Plugin authors will sell products globally, this might cause an error in some case.

King Regards

KAZUKI

**Comment by michelve** [comment]
I have upgraded this functionality - thx
