### ISSUE TITLE
Unable to add Product of type "License Manager"

### ISSUE THREAD

**Issue by QuiNz0r** [michelve/software-license-manager#4]
**Describe the bug**
Can't add License Product with attribute "License Manager" to woocommerce

**To Reproduce**
1. Add New Product with "License Manager" checked
2. Try to Publish/Update Product
3. License Manager is unchecked again and all options lost

**Expected behavior**
License Product type should be saved

**Comment by QuiNz0r** [comment]
I just noticed that also SERIAL Key prefix Setting is not saved. Any Ideas?

**Comment by michelve** [comment]
@QuiNz0r - I will look into this issue you are having. Meanwhile for the setting to take place go inside the settings page and click save to re-save them if you are coming from the original plugin

**Comment by michelve** [comment]
Issue has been resolved - thank you for the collaboration. See version release here https://github.com/michelve/software-license-manager/releases/tag/5.0.5
