### ISSUE TITLE
Would you mind using escape functions. 

### ISSUE THREAD

**Issue by k-kikuchi-idea-hack** [michelve/software-license-manager#40]
Thank you for providing good support and creating wonderful plugin.

I found that you don't use escape functions for output strings and url.

https://developer.wordpress.org/reference/functions/esc_html__/ (Escape and translation)
https://developer.wordpress.org/reference/functions/esc_html/ (Escape only)
https://developer.wordpress.org/reference/functions/esc_attr__/ (Escape and translation)
https://developer.wordpress.org/reference/functions/esc_attr/ (Escape only)
https://developer.wordpress.org/reference/functions/esc_url/

Example
`<?php echo __('Order', 'softwarelicensemanager'); ?>`
is should be
`<?php echo esc_html__('Order', 'softwarelicensemanager'); ?>`

When you have a time, it is better to add escape to improve security.

KIng Regards

KAZUKI

**Comment by michelve** [comment]
@k-kikuchi-idea-hack - thx some much for the the previous help, i am a bit busy lately with work, if you want to do a pull request i will happily accept the pull, also sorry for the delay idk why i am not receiving lately GitHub notifications
