### ISSUE TITLE
Would you ming adding toggle button to open license infor panel in wc_licenses_class.php

### ISSUE THREAD

**Issue by k-kikuchi-idea-hack** [michelve/software-license-manager#44]
Hello

Thank you for providing this good plugin, so that my business was much better.

On License management page (for WooCommerce), there is no UI to open detailed information for each license.
<img width="1248" alt="スクリーンショット 2020-09-11 8 16 22" src="https://user-images.githubusercontent.com/34845219/92822406-160b2900-f407-11ea-9c97-70847f617e59.png">

<img width="1252" alt="スクリーンショット 2020-09-11 8 15 55" src="https://user-images.githubusercontent.com/34845219/92822355-07bd0d00-f407-11ea-806d-8cf6ea572668.png">

I think users are really hard to find the way to show detailed information for each license.

Would you mind adding toggle button for improving UI & UX

Thank you in advance.
King Regards
KAZUKI

**Comment by michelve** [comment]
@k-kikuchi-idea-hack what theme are you using?
also do u have bootstrap library enabled or disabled ?

**Comment by michelve** [comment]
feature added for next version release
