### ISSUE TITLE
I cannot delete an actively licensed device from the license manager 

### ISSUE THREAD

**Issue by trescatorce** [michelve/software-license-manager#47]
I'm sorry I don't know if it's a mistake or if something has changed.

In previous versions, you could remove a device by clicking the '**Remove**' button in the '**Devices and Domains**' section

Now it shows me a message saying "**License key was not deactivated**!" and the selected device ID is not deleted.

I attach a screenshot with the error message displayed.
![sshot](https://user-images.githubusercontent.com/44380660/93941813-7e270c80-fd2f-11ea-8c3d-754b81312bb5.png)

It **worked fine** for me in version **5.5.1**
Then I moved to 5.5.6 and from there to 5.5.9 the same thing happens to me

Thank you so infinitely for your work!

**Comment by michelve** [comment]
i will take a look at this, sorry for the delays just very busy lately with work.
