### ISSUE TITLE
Problem in the process of activating and deactivating user-side licenses

### ISSUE THREAD

**Issue by ali110309** [michelve/software-license-manager#52]
Hello good time
I used the sample code you put in the plugin in my plugin. When I activate the license user on my site, the information on the server side of my license is sent and it is registered in the license management section of my site, but some errors are displayed on the user side.
I uncommented the var_dump in the code and took a screenshot of what was displayed
screenshot:
[https://nimb.ws/zYgymo](url)

Sample of my plugin code:
[https://drive.google.com/file/d/1Urat7QsR2wIY9HYkySWw4Mfe6CcjP7zY/view?usp=sharing](url)

**Comment by michelve** [comment]
@ali110309 - issue should be fixed now in the latest version
