### ISSUE TITLE
Renewals

### ISSUE THREAD

**Issue by snxraven** [michelve/software-license-manager#55]
Hello Guys,

I think this may be my favorite wordpress plugin to date. 

However, I am a little confused a bout how renewals work within WooCommerce. 

Ive made licenses for my products, and the licenses work great and expire after 30 days, but I am confused how to allow woocommerce to renew the same license. 

Regards,
Raven

**Comment by snxraven** [comment]
I have gotten a "workable" solution for this issue, however, It would be really nice to have a fully integrated solution

For this to work, ive used the wordpress plugin "PPOM for WooCommerce by N-MEDIA" to create a custom input field on a new product called "Renew Service"

I then added the following code to my functions.php file for my theme for woocommerce this is using the update method:

`if ($product_name == "Renew Service"){
	
$today = date('Y-m-d');
$next_due_date = date('Y-m-d', strtotime($today. ' +30 days'));
echo "New Due Date: " . $next_due_date;

// OUTPUT
  $items = $order->get_items();

    foreach ( $items as $item_id => $item_data ) {

        // Using get_item_meta() method
        echo 'License Key For this Order is: ' . $order->get_item_meta($item_id, 'licenseid', true) . '';
	
		
		wp_remote_post ("https://chksrv.pro/?secret_key=KEYHERE&slm_action=slm_update&license_key=" . $order->get_item_meta($item_id, 'licenseid', true) . "&lic_status=Active&max_allowed_domains=1&date_expiry=" . $next_due_date, $arg );

    }`

Once the payment is processed, wordpress post requests the update in expiration. 

I hope this helps some folks

**Comment by michelve** [comment]
i never had the time to implement the renewal process using woocommerce, but your input and help is greatly appreciated

**Comment by snxraven** [comment]
That is no problem. 

This solution is actually pretty decent. I may make updates to what I have come up with and update to this Issue. As I am just now getting back into php after a few years I may take some time to get a pull request done with an actual integrated solution.
