### ISSUE TITLE
missing key

### ISSUE THREAD

**Issue by rigler86** [michelve/software-license-manager#58]
after creating a key and running activate I am getting this response. i also tried the slm_deactivate getting same response. 
{"result":"error","message":"Cannot update license, license key not found.","error_code":260}

check works fine. i am running 5.5.9. i also tried with 5.5.12

what could be causing this issue.

**Comment by jordan-mace** [comment]
If you try an activation/deactivation and don't provide either a registered_devices or registered_domains param it will give that message
