### ISSUE TITLE
License expired

### ISSUE THREAD

**Issue by Denis74F** [michelve/software-license-manager#60]
Hi,
I haven't been able to fix a problem for days with the license expired.
The problem is this:
when an expired license of the "example" site is imposed by the license manager, the license on the "example" site continues to work.
Only if I deactivate and reactivate the license from the "example" site, will the message appear that the license has expired.
Is there a way to make it expire without having to do this procedure? Otherwise the plugin to which I have applied this license continues to work.

Thanks

Regards

Denis

**Comment by Denis74F** [comment]
Hi,
I realized where I was wrong.

Thanks anyway.

Regards

Denis

**Comment by michelve** [comment]
thx
