### ISSUE TITLE
Backup settings and subscribers

### ISSUE THREAD

**Issue by rigler86** [michelve/software-license-manager#61]
How can i backup just the settings and subscribers. I want to move everything to a new site and somain completely. I have someone taking over my project. Want to keep the subscribers on the move.

**Comment by michelve** [comment]
you will have to back up the user's license table manually using PHPMyAdmin or somehtign similar

here are the tables it uses:

// Tables
$wpdb->prefix . "lic_key_tbl");
$wpdb->prefix . "lic_reg_domain_tbl");
$wpdb->prefix . "lic_reg_devices_tbl");
$wpdb->prefix . "lic_log_tbl");

all the settings are saved here under this row inside the options table -- slm_plugin_options

**Comment by rigler86** [comment]
Will this keep the license keys as well?

**Comment by michelve** [comment]
yes it will
