### ISSUE TITLE
[Question] Smart way to integrate license product type with WC subscriptions?

### ISSUE THREAD

**Issue by brandtOSS** [michelve/software-license-manager#86]
First of all: thank you for creating and maintaining this awesome piece of software!

I want to use SLM in combination with WooCommerce (on the same WP install).
My software products are going to be sold via [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions) (i.e. auto-renewal). Hence, I believe I cannot use the SLM license product type.

Before I go down the rabbit hole to digest the great work in the [WooCommerce code folder](https://github.com/michelve/software-license-manager/tree/master/woocommerce/includes) to get my own integration going: is this really necessary?

Or does the SLM WooCommerce integration also work with the Subscriptions somehow?
Or can one somehow get a subscription-style auto-renewal with the SLM product type?

Thank you!

**Comment by snxraven** [comment]
If you figure this out please let me know it does seem to need to be coded

**Comment by michelve** [comment]
@brandtOSS - this was something I had road mapped but never had the time to get into it, at this point the current version does not support [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions) - the effort needed for this is medium.

I will happy to contribute if needed, during my spare time.
