### ISSUE TITLE
Double Plugin entries

### ISSUE THREAD

**Issue by Narimm** [michelve/software-license-manager#88]
**Describe the bug**
There are 2 entries on the plugin management page. One refers to the version available on Wordpress.org's plugin pages.  The other refers to this plugin,

**To Reproduce**
Install on a fresh WP 

**Expected behavior**
Only one entry

**Screenshots**
![image](https://user-images.githubusercontent.com/2214955/196576207-acae3b80-18b9-4d6c-a527-3c9e836f4dae.png)

**Comment by fabolivark** [comment]
The problem occurs because WordPress is reading the metadata in the file  index.php
´´´
<?php
    //Plugin Name: Software License Manager
    //Author: Michel Veli

?>
´´´

**Comment by Narimm** [comment]
This is fixed by  #97 which includes a update to the underlying PUC system
