### ISSUE TITLE
Spanish Language

### ISSUE THREAD

**Issue by simple-simple** [michelve/software-license-manager#92]
Hi, I'm Gustavo from Neuquén, Argentina and I'm trying the "SLM" plugin for a project, but I can't get the Spanish language to take hold. I already tried everything. I made sure to put the Spanish language of Argentina in WordPress but it does not take it. Nor does it test in Spanish from Spain, it only always shows it to me in English...

Any suggestions what could be going on?

Thank you very much for any help you can give me.

Cheers!

Gustavo

**Comment by michelve** [comment]
it should work
language files are located here: [software-license-manager](https://github.com/michelve/software-license-manager)/[i18n](https://github.com/michelve/software-license-manager/tree/master/i18n)/languages/ 

I will take a look

**Comment by michelve** [comment]
It is still in beta, but most of this issue has been fixed in the latest dev branch https://github.com/michelve/software-license-manager/tree/dev-6.1.0, hopefully i can release the stable version by next week
