### ISSUE TITLE
Automatic generation of license code for existing customer orders (for orders before installing the plugin)

### ISSUE THREAD

**Issue by themefour** [michelve/software-license-manager#96]
This plugin is great. But a very, very important possibility is missing in it. I would like you to add an option to automatically generate license codes for customers for existing WooCommerce orders. Can you add this? I need it very much.

**Comment by michelve** [comment]
i will add this to the upcoming release version

**Comment by michelve** [comment]
Request added under dev branch https://github.com/michelve/software-license-manager/commit/fe6de7bc497f33c5c5a46b8b28f30246f266cf12
