### ISSUE TITLE
Issue with add to cart button

### ISSUE THREAD

**Issue by ricardo777** [michelve/software-license-manager#99]
Hello, I have some trouble with missing the add to cart button, for at least when using Divi builder. The following options resolve the issue.

Via Snippet:

```
/**
 * Display the 'Add to Cart' button for 'slm_license' product type.
 * This hooks into the custom product type's add to cart action and 
 * uses the default WooCommerce simple product's add to cart functionality.
 */
add_action("woocommerce_slm_license_add_to_cart", function() {
    do_action('woocommerce_simple_add_to_cart');
});
```

Or adding the following action to the code for example register_template.php 

```
function add_to_cart_button() {
    wc_get_template( 'single-product/add-to-cart/simple.php' );
}
add_action( 'woocommerce_slm_license_add_to_cart', 'add_to_cart_button' );

```
I am new into Woocommerce so possible this is not the right way, but could not getting anything else working.

**Comment by michelve** [comment]
i will look into this.

It is still in beta, but most of this issue has been fixed in the latest dev branch https://github.com/michelve/software-license-manager/tree/dev-6.1.0, hopefully i can release the stable version by next week
